repos:
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.16.1
  hooks:
  - id: gitleaks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  -   id: check-yaml
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
  -   id: check-json
  -   id: check-added-large-files
- repo: https://github.com/ambv/black
  rev: 23.1.0
  hooks:
    - id: black
      args:
        - --line-length=110
        - --exclude="""\.git |
          \.__pycache__|
          \.hg|
          \.mypy_cache|
          \.tox|
          \.venv|
          _build|
          buck-out|
          build|
          dist"""
      language_version: python3
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
      args:
        - --profile=black
        - --filter-files
        - --line-length=110
- repo: https://github.com/pycqa/autoflake
  rev: v2.0.2
  hooks:
    - id: autoflake
      args:
        - --exclude="""\.git |
          \.__pycache__|
          \.hg|
          \.mypy_cache|
          \.tox|
          \.venv|
          _build|
          buck-out|
          build|
          dist"""
- repo: https://github.com/pycqa/pylint
  rev: v2.17.1
  hooks:
    -   id: pylint
        args:
        - --rcfile=.pylintrc
